name: Terraform Deploy

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  terraform:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    environment: aws
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set AWS credentials
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
        echo "AWS_DEFAULT_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        export AWS_DEFAULT_REGION=${{ secrets.AWS_REGION }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Initialize Terraform
      run: |
        cd Terraform-VPC
        terraform init
      # env:
      #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Plan Terraform changes
      run: |
        cd Terraform-VPC
        terraform plan -out=tfplan

    - name: Apply Terraform changes
      run: |
        cd Terraform-VPC
        terraform apply --auto-approve

    - name: Clean up
      run: rm Terraform-VPC/tfplan
      
